export enum ColorTheme {
  DEFAULT = "default",
  DARK = "dark",
  LOLLYPOP = "lollypop",
  BROWN_BOY = "brown-boy",
  BOOTSTRAP = "bootstrap",
  BABYBLUE = "baby-blue",
}

export enum FontTheme {
  DEFAULT = "sans-serif",
  TIMES_NEW_ROMAN = "Times New Roman",
  BAHNSCHRIFT = "Bahnschrift",
  DANCINGSCRIPTREGULAR = "dancingscriptregular",
}

export enum SettingType {
  SHOULD_SCROLL_TO_TOP = "SHOULD_SCROLL_TO_TOP",
  SHOULD_SHOW_MISSION_COMPLETED_COLOR = "SHOULD_SHOW_MISSION_COMPLETED_COLOR",
  COLOR_THEME = "COLOR_THEME",
  FONT_THEME = "FONT_THEME",
  SHOULD_ALERT_DELETE_COUNTER = "SHOULD_ALERT_DELETE_COUNTER",
  SHOULD_ALERT_DELETE_MISSION = "SHOULD_ALERT_DELETE_MISSION",
  SHOULD_STRIKE_COMPLETED_MISSION = "SHOULD_STRIKE_COMPLETED_MISSION",
}
